# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _shared.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\r_shared.proto\"b\n\x0eResponseStatus\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x19\n\x0fresponseMessage\x18\x02 \x01(\tH\x00\x12\x16\n\x0c\x65rrorMessage\x18\x03 \x01(\tH\x00\x42\t\n\x07message\"\x10\n\x02id\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x04name\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '_shared_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSESTATUS._serialized_start=17
  _RESPONSESTATUS._serialized_end=115
  _ID._serialized_start=117
  _ID._serialized_end=133
  _NAME._serialized_start=135
  _NAME._serialized_end=155
# @@protoc_insertion_point(module_scope)
