# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ip-mgr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ipAddress_pb2 as ipAddress__pb2
try:
  __shared__pb2 = ipAddress__pb2.__shared__pb2
except AttributeError:
  __shared__pb2 = ipAddress__pb2._shared_pb2
import subnet_pb2 as subnet__pb2
try:
  __shared__pb2 = subnet__pb2.__shared__pb2
except AttributeError:
  __shared__pb2 = subnet__pb2._shared_pb2
import vlan_pb2 as vlan__pb2
try:
  __shared__pb2 = vlan__pb2.__shared__pb2
except AttributeError:
  __shared__pb2 = vlan__pb2._shared_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cip-mgr.proto\x1a\x0fipAddress.proto\x1a\x0csubnet.proto\x1a\nvlan.proto2\xb9\x02\n\x10IpAddressService\x12-\n\x10GetIpAddressById\x12\x03.id\x1a\x12.IpAddressResponse\"\x00\x12\x31\n\x12GetIpAddressByName\x12\x05.name\x1a\x12.IpAddressResponse\"\x00\x12\x31\n\x14GetIpAddressBySubnet\x12\x03.id\x1a\x12.IpAddressResponse\"\x00\x12\x30\n\x0c\x41\x64\x64IpAddress\x12\n.ipAddress\x1a\x12.IpAddressResponse\"\x00\x12\x33\n\x0fUpdateIpAddress\x12\n.ipAddress\x1a\x12.IpAddressResponse\"\x00\x12)\n\x0f\x44\x65leteIpAddress\x12\x03.id\x1a\x0f.ResponseStatus\"\x00\x32\x92\x02\n\rSubnetService\x12\'\n\rGetSubnetById\x12\x03.id\x1a\x0f.SubnetResponse\"\x00\x12+\n\x0fGetSubnetByName\x12\x05.name\x1a\x0f.SubnetResponse\"\x00\x12.\n\x14GetSubnetByIpAddress\x12\x03.id\x1a\x0f.SubnetResponse\"\x00\x12\'\n\tAddSubnet\x12\x07.subnet\x1a\x0f.SubnetResponse\"\x00\x12*\n\x0cUpdateSubnet\x12\x07.subnet\x1a\x0f.SubnetResponse\"\x00\x12&\n\x0c\x44\x65leteSubnet\x12\x03.id\x1a\x0f.ResponseStatus\"\x00\x32\xf6\x01\n\x0bvLANService\x12#\n\x0bGetVlanById\x12\x03.id\x1a\r.vLANResponse\"\x00\x12\'\n\rGetVlanByName\x12\x05.name\x1a\r.vLANResponse\"\x00\x12*\n\x12GetVlanByIpAddress\x12\x03.id\x1a\r.vLANResponse\"\x00\x12!\n\x07\x41\x64\x64Vlan\x12\x05.vlan\x1a\r.vLANResponse\"\x00\x12$\n\nUpdateVlan\x12\x05.vlan\x1a\r.vLANResponse\"\x00\x12$\n\nDeleteVlan\x12\x03.id\x1a\x0f.ResponseStatus\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ip_mgr_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IPADDRESSSERVICE._serialized_start=60
  _IPADDRESSSERVICE._serialized_end=373
  _SUBNETSERVICE._serialized_start=376
  _SUBNETSERVICE._serialized_end=650
  _VLANSERVICE._serialized_start=653
  _VLANSERVICE._serialized_end=899
# @@protoc_insertion_point(module_scope)
