# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vlan.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import _shared_pb2 as __shared__pb2

from _shared_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nvlan.proto\x1a\r_shared.proto\"w\n\x04vlan\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nvlanNumber\x18\x03 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x14\n\x0c\x64\x61taLastSeen\x18\x05 \x01(\t\x12\x16\n\x0e\x64\x61teLastEdited\x18\x06 \x01(\t\"D\n\x0cvLANResponse\x12\x13\n\x04vlan\x18\x01 \x01(\x0b\x32\x05.vlan\x12\x1f\n\x06status\x18\x02 \x01(\x0b\x32\x0f.ResponseStatusP\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vlan_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VLAN._serialized_start=29
  _VLAN._serialized_end=148
  _VLANRESPONSE._serialized_start=150
  _VLANRESPONSE._serialized_end=218
# @@protoc_insertion_point(module_scope)
