version: '3'
services:
  ipMgr:
    image: photon:latest
    restart: always
    #env_file: ./.env.dev
    build: .
    ports:
      - 5005:5005
    networks:
      - db_network
      - app_network
    depends_on: 
      - postgres
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PyIPAM-Passw0rd123!
      POSTGRES_DB: IP-Mgr
    image: postgres:15
    networks:
      - db_network
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data-15.1:/var/lib/postgresql/data
networks:
  db_network:
    driver: bridge
  app_network:
    driver: bridge

volumes: 
  postgres_data: