# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import _shared_pb2 as __shared__pb2
import ipAddress_pb2 as ipAddress__pb2


class IpAddressServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIpAddressById = channel.unary_unary(
                '/IpAddressService/GetIpAddressById',
                request_serializer=__shared__pb2.id.SerializeToString,
                response_deserializer=ipAddress__pb2.IpAddressResponse.FromString,
                )
        self.GetIpAddressByName = channel.unary_unary(
                '/IpAddressService/GetIpAddressByName',
                request_serializer=__shared__pb2.name.SerializeToString,
                response_deserializer=ipAddress__pb2.IpAddressResponse.FromString,
                )
        self.GetIpAddressBySubnet = channel.unary_unary(
                '/IpAddressService/GetIpAddressBySubnet',
                request_serializer=__shared__pb2.id.SerializeToString,
                response_deserializer=ipAddress__pb2.IpAddressResponse.FromString,
                )
        self.AddIpAddress = channel.unary_unary(
                '/IpAddressService/AddIpAddress',
                request_serializer=ipAddress__pb2.ipAddress.SerializeToString,
                response_deserializer=ipAddress__pb2.IpAddressResponse.FromString,
                )
        self.UpdateIpAddress = channel.unary_unary(
                '/IpAddressService/UpdateIpAddress',
                request_serializer=ipAddress__pb2.ipAddress.SerializeToString,
                response_deserializer=ipAddress__pb2.IpAddressResponse.FromString,
                )
        self.DeleteIpAddress = channel.unary_unary(
                '/IpAddressService/DeleteIpAddress',
                request_serializer=__shared__pb2.id.SerializeToString,
                response_deserializer=__shared__pb2.ResponseStatus.FromString,
                )


class IpAddressServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIpAddressById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIpAddressByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIpAddressBySubnet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddIpAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIpAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIpAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IpAddressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIpAddressById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIpAddressById,
                    request_deserializer=__shared__pb2.id.FromString,
                    response_serializer=ipAddress__pb2.IpAddressResponse.SerializeToString,
            ),
            'GetIpAddressByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIpAddressByName,
                    request_deserializer=__shared__pb2.name.FromString,
                    response_serializer=ipAddress__pb2.IpAddressResponse.SerializeToString,
            ),
            'GetIpAddressBySubnet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIpAddressBySubnet,
                    request_deserializer=__shared__pb2.id.FromString,
                    response_serializer=ipAddress__pb2.IpAddressResponse.SerializeToString,
            ),
            'AddIpAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.AddIpAddress,
                    request_deserializer=ipAddress__pb2.ipAddress.FromString,
                    response_serializer=ipAddress__pb2.IpAddressResponse.SerializeToString,
            ),
            'UpdateIpAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIpAddress,
                    request_deserializer=ipAddress__pb2.ipAddress.FromString,
                    response_serializer=ipAddress__pb2.IpAddressResponse.SerializeToString,
            ),
            'DeleteIpAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIpAddress,
                    request_deserializer=__shared__pb2.id.FromString,
                    response_serializer=__shared__pb2.ResponseStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IpAddressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IpAddressService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIpAddressById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IpAddressService/GetIpAddressById',
            __shared__pb2.id.SerializeToString,
            ipAddress__pb2.IpAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIpAddressByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IpAddressService/GetIpAddressByName',
            __shared__pb2.name.SerializeToString,
            ipAddress__pb2.IpAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIpAddressBySubnet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IpAddressService/GetIpAddressBySubnet',
            __shared__pb2.id.SerializeToString,
            ipAddress__pb2.IpAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddIpAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IpAddressService/AddIpAddress',
            ipAddress__pb2.ipAddress.SerializeToString,
            ipAddress__pb2.IpAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateIpAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IpAddressService/UpdateIpAddress',
            ipAddress__pb2.ipAddress.SerializeToString,
            ipAddress__pb2.IpAddressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteIpAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IpAddressService/DeleteIpAddress',
            __shared__pb2.id.SerializeToString,
            __shared__pb2.ResponseStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
